"""empty message

Revision ID: a5cb2985183a
Revises: 
Create Date: 2025-02-02 21:54:19.036624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a5cb2985183a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ch',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('dims', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('sexual', sa.Float(), nullable=True),
    sa.Column('violence', sa.Float(), nullable=True),
    sa.Column('votecount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('original', sa.String(), nullable=True),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('blood_type', sa.String(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('bust', sa.Integer(), nullable=True),
    sa.Column('waist', sa.Integer(), nullable=True),
    sa.Column('hips', sa.Integer(), nullable=True),
    sa.Column('cup', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('birthday', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('sex', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cv',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.Column('thumbnail_dims', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('dims', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('sexual', sa.Float(), nullable=True),
    sa.Column('violence', sa.Float(), nullable=True),
    sa.Column('votecount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extlinks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('original', sa.String(), nullable=True),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('lang', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('releases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('alttitle', sa.String(), nullable=True),
    sa.Column('languages', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('platforms', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('media', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('released', sa.String(), nullable=True),
    sa.Column('minage', sa.Integer(), nullable=True),
    sa.Column('patch', sa.Boolean(), nullable=True),
    sa.Column('freeware', sa.Boolean(), nullable=True),
    sa.Column('uncensored', sa.Boolean(), nullable=True),
    sa.Column('official', sa.Boolean(), nullable=True),
    sa.Column('has_ero', sa.Boolean(), nullable=True),
    sa.Column('resolution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('voiced', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('gtin', sa.String(), nullable=True),
    sa.Column('catalog', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sf',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.Column('thumbnail_dims', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('dims', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('sexual', sa.Float(), nullable=True),
    sa.Column('violence', sa.Float(), nullable=True),
    sa.Column('votecount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('aid', sa.Integer(), nullable=True),
    sa.Column('ismain', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('original', sa.String(), nullable=True),
    sa.Column('lang', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('aliases', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('searchable', sa.Boolean(), nullable=True),
    sa.Column('applicable', sa.Boolean(), nullable=True),
    sa.Column('vn_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('searchable', sa.Boolean(), nullable=True),
    sa.Column('applicable', sa.Boolean(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('alttitle', sa.String(), nullable=True),
    sa.Column('titles', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('olang', sa.String(), nullable=True),
    sa.Column('devstatus', sa.Integer(), nullable=True),
    sa.Column('released', sa.String(), nullable=True),
    sa.Column('languages', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('platforms', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('length_minutes', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('average', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('votecount', sa.Integer(), nullable=True),
    sa.Column('editions', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appearances',
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('vn_id', sa.String(), nullable=False),
    sa.Column('release_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.ForeignKeyConstraint(['vn_id'], ['vns.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'vn_id', 'release_id')
    )
    op.create_table('character_ch',
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('ch_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ch_id'], ['ch.id'], ),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'ch_id')
    )
    op.create_table('character_trait',
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('trait_id', sa.String(), nullable=False),
    sa.Column('spoiler', sa.Integer(), nullable=True),
    sa.Column('lie', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['trait_id'], ['traits.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'trait_id')
    )
    op.create_table('character_vn',
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('vn_id', sa.String(), nullable=False),
    sa.Column('spoiler', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['vn_id'], ['vns.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'vn_id')
    )
    op.create_table('producer_extlink',
    sa.Column('producer_id', sa.String(), nullable=False),
    sa.Column('extlink_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['extlink_id'], ['extlinks.id'], ),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ),
    sa.PrimaryKeyConstraint('producer_id', 'extlink_id')
    )
    op.create_table('release_cv',
    sa.Column('release_id', sa.String(), nullable=False),
    sa.Column('cv_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('vn', sa.String(), nullable=True),
    sa.Column('languages', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('photo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cv.id'], ),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.ForeignKeyConstraint(['vn'], ['vns.id'], ),
    sa.PrimaryKeyConstraint('release_id', 'cv_id')
    )
    op.create_table('release_extlink',
    sa.Column('release_id', sa.String(), nullable=False),
    sa.Column('extlink_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['extlink_id'], ['extlinks.id'], ),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.PrimaryKeyConstraint('release_id', 'extlink_id')
    )
    op.create_table('release_producer',
    sa.Column('release_id', sa.String(), nullable=False),
    sa.Column('producer_id', sa.String(), nullable=False),
    sa.Column('developer', sa.Boolean(), nullable=True),
    sa.Column('publisher', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.PrimaryKeyConstraint('release_id', 'producer_id')
    )
    op.create_table('release_vn',
    sa.Column('release_id', sa.String(), nullable=False),
    sa.Column('vn_id', sa.String(), nullable=False),
    sa.Column('rtype', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.ForeignKeyConstraint(['vn_id'], ['vns.id'], ),
    sa.PrimaryKeyConstraint('release_id', 'vn_id')
    )
    op.create_table('staff_extlink',
    sa.Column('staff_id', sa.String(), nullable=False),
    sa.Column('extlink_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['extlink_id'], ['extlinks.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('staff_id', 'extlink_id')
    )
    op.create_table('va',
    sa.Column('vn_id', sa.String(), nullable=False),
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('staff_id', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['vn_id'], ['vns.id'], ),
    sa.PrimaryKeyConstraint('vn_id', 'character_id', 'staff_id')
    )
    op.create_table('vn_cv',
    sa.Column('vn_id', sa.String(), nullable=False),
    sa.Column('cv_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cv_id'], ['cv.id'], ),
    sa.ForeignKeyConstraint(['vn_id'], ['vns.id'], ),
    sa.PrimaryKeyConstraint('vn_id', 'cv_id')
    )
    op.create_table('vn_extlink',
    sa.Column('vn_id', sa.String(), nullable=False),
    sa.Column('extlink_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['extlink_id'], ['extlinks.id'], ),
    sa.ForeignKeyConstraint(['vn_id'], ['vns.id'], ),
    sa.PrimaryKeyConstraint('vn_id', 'extlink_id')
    )
    op.create_table('vn_producer',
    sa.Column('vn_id', sa.String(), nullable=False),
    sa.Column('producer_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ),
    sa.ForeignKeyConstraint(['vn_id'], ['vns.id'], ),
    sa.PrimaryKeyConstraint('vn_id', 'producer_id')
    )
    op.create_table('vn_sf',
    sa.Column('vn_id', sa.String(), nullable=False),
    sa.Column('sf_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sf_id'], ['sf.id'], ),
    sa.ForeignKeyConstraint(['vn_id'], ['vns.id'], ),
    sa.PrimaryKeyConstraint('vn_id', 'sf_id')
    )
    op.create_table('vn_staff',
    sa.Column('vn_id', sa.String(), nullable=False),
    sa.Column('staff_id', sa.String(), nullable=False),
    sa.Column('eid', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['vn_id'], ['vns.id'], ),
    sa.PrimaryKeyConstraint('vn_id', 'staff_id')
    )
    op.create_table('vn_tag',
    sa.Column('vn_id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('spoiler', sa.Integer(), nullable=True),
    sa.Column('lie', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['vn_id'], ['vns.id'], ),
    sa.PrimaryKeyConstraint('vn_id', 'tag_id')
    )
    op.create_table('vn_vn',
    sa.Column('vn1_id', sa.String(), nullable=False),
    sa.Column('vn2_id', sa.String(), nullable=False),
    sa.Column('relation', sa.String(), nullable=True),
    sa.Column('relation_official', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['vn1_id'], ['vns.id'], ),
    sa.ForeignKeyConstraint(['vn2_id'], ['vns.id'], ),
    sa.PrimaryKeyConstraint('vn1_id', 'vn2_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vn_vn')
    op.drop_table('vn_tag')
    op.drop_table('vn_staff')
    op.drop_table('vn_sf')
    op.drop_table('vn_producer')
    op.drop_table('vn_extlink')
    op.drop_table('vn_cv')
    op.drop_table('va')
    op.drop_table('staff_extlink')
    op.drop_table('release_vn')
    op.drop_table('release_producer')
    op.drop_table('release_extlink')
    op.drop_table('release_cv')
    op.drop_table('producer_extlink')
    op.drop_table('character_vn')
    op.drop_table('character_trait')
    op.drop_table('character_ch')
    op.drop_table('appearances')
    op.drop_table('vns')
    op.drop_table('traits')
    op.drop_table('tags')
    op.drop_table('staff')
    op.drop_table('sf')
    op.drop_table('releases')
    op.drop_table('producers')
    op.drop_table('extlinks')
    op.drop_table('cv')
    op.drop_table('characters')
    op.drop_table('ch')
    # ### end Alembic commands ###
