[project]
name = "python-common"
version = "0.1.0"
description = "Add a short description here"
authors = ["Efrain Jack <1731237095@qq.com>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]

[dependencies]
