[project]
authors = ["KOBAYASHI <example@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "python-common"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.5,<4"
