[project]
authors = ["KOBAYASHI <example@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "show-video-cover"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
pillow = ">=10.4.0,<11"
ffmpeg-python = ">=0.2.0,<0.3"
python = "==3.11"

[pypi-dependencies]
chafa-py = { path = '.\dependence\chafa.py-1.1.2-cp311-cp311-win_amd64.whl' }
