"""empty message

Revision ID: 078eb59cc5f1
Revises: 144a1621fbd5
Create Date: 2024-12-10 04:53:21.044019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078eb59cc5f1'
down_revision = '144a1621fbd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_email_deleted_at', type_='unique')
        batch_op.create_unique_constraint('uq_email_deleted_at', ['email', 'is_active'])
        batch_op.drop_constraint('uq_username_deleted_at', type_='unique')
        batch_op.create_unique_constraint('uq_username_deleted_at', ['username', 'is_active'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_username_deleted_at', type_='unique')
        batch_op.create_unique_constraint('uq_username_deleted_at', ['username', 'deleted_at'])
        batch_op.drop_constraint('uq_email_deleted_at', type_='unique')
        batch_op.create_unique_constraint('uq_email_deleted_at', ['email', 'deleted_at'])

    # ### end Alembic commands ###
