"""empty message

Revision ID: 715e5150b978
Revises: 078eb59cc5f1
Create Date: 2024-12-10 05:09:26.253281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715e5150b978'
down_revision = '078eb59cc5f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.drop_constraint('uq_name_uid_deleted_at', type_='unique')
        batch_op.create_unique_constraint('uq_name_uid_deleted_at', ['name', 'uid', 'is_active'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.drop_constraint('uq_name_deleted_at', type_='unique')
        batch_op.create_unique_constraint('uq_name_deleted_at', ['name', 'is_active'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint('uq_name_deleted_at', type_='unique')
        batch_op.create_unique_constraint('uq_name_deleted_at', ['name', 'deleted_at'])
        batch_op.drop_column('is_active')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_constraint('uq_name_uid_deleted_at', type_='unique')
        batch_op.create_unique_constraint('uq_name_uid_deleted_at', ['name', 'uid', 'deleted_at'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
