"""empty message

Revision ID: 2b3041c400e5
Revises: 496df39d7ef9
Create Date: 2025-02-09 13:27:17.334754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b3041c400e5'
down_revision = '496df39d7ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('last_modified_at')

    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('last_modified_at')

    with op.batch_alter_table('cvt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('last_modified_at')

    with op.batch_alter_table('sf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('last_modified_at')

    with op.batch_alter_table('sft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('last_modified_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('sf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('cvt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('ch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
