"""empty message

Revision ID: 82150dd21617
Revises: 6e346749e04c
Create Date: 2025-02-17 00:37:11.711210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82150dd21617'
down_revision = '6e346749e04c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_categories', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_charactercategory_user_category', ['user_id', 'category_name'])

    with op.batch_alter_table('producer_categories', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_producercategory_user_category', ['user_id', 'category_name'])

    with op.batch_alter_table('staff_categories', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_staffcategory_user_category', ['user_id', 'category_name'])

    with op.batch_alter_table('vn_categories', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_vncategory_user_category', ['user_id', 'category_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vn_categories', schema=None) as batch_op:
        batch_op.drop_constraint('uq_vncategory_user_category', type_='unique')

    with op.batch_alter_table('staff_categories', schema=None) as batch_op:
        batch_op.drop_constraint('uq_staffcategory_user_category', type_='unique')

    with op.batch_alter_table('producer_categories', schema=None) as batch_op:
        batch_op.drop_constraint('uq_producercategory_user_category', type_='unique')

    with op.batch_alter_table('character_categories', schema=None) as batch_op:
        batch_op.drop_constraint('uq_charactercategory_user_category', type_='unique')

    # ### end Alembic commands ###
