"""empty message

Revision ID: 2d5057ad0a52
Revises: 6ebfff4e4200
Create Date: 2025-04-09 16:20:39.268111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d5057ad0a52'
down_revision = '6ebfff4e4200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publishers', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vns', schema=None) as batch_op:
        batch_op.drop_column('publishers')

    # ### end Alembic commands ###
