"""empty message

Revision ID: 2e281c641c3f
Revises: 
Create Date: 2025-02-20 13:58:56.930271

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e281c641c3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('original', sa.String(), nullable=True),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('blood_type', sa.String(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('bust', sa.Integer(), nullable=True),
    sa.Column('waist', sa.Integer(), nullable=True),
    sa.Column('hips', sa.Integer(), nullable=True),
    sa.Column('cup', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.String(), nullable=True),
    sa.Column('sex', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('image', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vns', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('traits', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('seiyuu', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('original', sa.String(), nullable=True),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('lang', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extlinks', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('releases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('alttitle', sa.String(), nullable=True),
    sa.Column('languages', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('platforms', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('media', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('vns', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('producers', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('images', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('released', sa.String(), nullable=True),
    sa.Column('minage', sa.Integer(), nullable=True),
    sa.Column('patch', sa.Boolean(), nullable=True),
    sa.Column('freeware', sa.Boolean(), nullable=True),
    sa.Column('uncensored', sa.Boolean(), nullable=True),
    sa.Column('official', sa.Boolean(), nullable=True),
    sa.Column('has_ero', sa.Boolean(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('voiced', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('gtin', sa.String(), nullable=True),
    sa.Column('catalog', sa.String(), nullable=True),
    sa.Column('extlinks', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('aid', sa.String(), nullable=True),
    sa.Column('ismain', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('original', sa.String(), nullable=True),
    sa.Column('lang', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extlinks', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('aliases', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('aid', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('searchable', sa.Boolean(), nullable=True),
    sa.Column('applicable', sa.Boolean(), nullable=True),
    sa.Column('vn_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('searchable', sa.Boolean(), nullable=True),
    sa.Column('applicable', sa.Boolean(), nullable=True),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('alttitle', sa.String(), nullable=True),
    sa.Column('titles', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('olang', sa.String(), nullable=True),
    sa.Column('devstatus', sa.Integer(), nullable=True),
    sa.Column('released', sa.String(), nullable=True),
    sa.Column('languages', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('platforms', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('image', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('length_minutes', sa.Integer(), nullable=True),
    sa.Column('length_votes', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('average', sa.Float(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('votecount', sa.Integer(), nullable=True),
    sa.Column('screenshots', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('relations', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('tags', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('developers', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('editions', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('staff', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('va', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('extlinks', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('characters', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('releases', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vns')
    op.drop_table('traits')
    op.drop_table('tags')
    op.drop_table('staff')
    op.drop_table('releases')
    op.drop_table('producers')
    op.drop_table('characters')
    # ### end Alembic commands ###
