"""empty message

Revision ID: 41fe0a0830a4
Revises: 
Create Date: 2025-02-13 15:38:51.521781

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '41fe0a0830a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seiyuu', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('seiyuu')

    # ### end Alembic commands ###
