"""empty message

Revision ID: 7c830c06be8f
Revises: 41fe0a0830a4
Create Date: 2025-02-16 13:46:24.539597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c830c06be8f'
down_revision = '41fe0a0830a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extlinks', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producers', schema=None) as batch_op:
        batch_op.drop_column('extlinks')

    # ### end Alembic commands ###
