# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pubsub.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpubsub.proto\x12\x06pubsub\"I\n\x07Message\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x0b\n\x03ttl\x18\x04 \x01(\x05\"!\n\x10SubscribeRequest\x12\r\n\x05topic\x18\x01 \x01(\t\"2\n\x0ePublishRequest\x12 \n\x07message\x18\x01 \x01(\x0b\x32\x0f.pubsub.Message\"\x07\n\x05\x45mpty2{\n\rPubSubService\x12\x38\n\tSubscribe\x12\x18.pubsub.SubscribeRequest\x1a\x0f.pubsub.Message0\x01\x12\x30\n\x07Publish\x12\x16.pubsub.PublishRequest\x1a\r.pubsub.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pubsub_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGE']._serialized_start=24
  _globals['_MESSAGE']._serialized_end=97
  _globals['_SUBSCRIBEREQUEST']._serialized_start=99
  _globals['_SUBSCRIBEREQUEST']._serialized_end=132
  _globals['_PUBLISHREQUEST']._serialized_start=134
  _globals['_PUBLISHREQUEST']._serialized_end=184
  _globals['_EMPTY']._serialized_start=186
  _globals['_EMPTY']._serialized_end=193
  _globals['_PUBSUBSERVICE']._serialized_start=195
  _globals['_PUBSUBSERVICE']._serialized_end=318
# @@protoc_insertion_point(module_scope)
