export const FULL_FORM = {
  "LANGUAGE": {
    ar: "Arabic",
    be: "Belarusian",
    bg: "Bulgarian",
    ca: "Catalan",
    ck: "Cherokee",
    cs: "Czech",
    da: "Danish",
    de: "German",
    el: "Greek",
    en: "English",
    eo: "Esperanto",
    es: "Spanish",
    et: "Estonian",
    eu: "Basque",
    fa: "Persian",
    fi: "Finnish",
    fr: "French",
    ga: "Irish",
    gd: "Scottish Gaelic",
    he: "Hebrew",
    hi: "Hindi",
    hr: "Croatian",
    hu: "Hungarian",
    id: "Indonesian",
    it: "Italian",
    iu: "Inuktitut",
    ja: "Japanese",
    ka: "Georgian",
    ko: "Korean",
    la: "Latin",
    lt: "Lithuanian",
    lv: "Latvian",
    mk: "Macedonian",
    ms: "Malay",
    nl: "Dutch",
    no: "Norwegian",
    pl: "Polish",
    "pt-br": "Portuguese (Brazilian)",
    "pt-pt": "Portuguese",
    pt: "Portuguese",
    ro: "Romanian",
    ru: "Russian",
    sk: "Slovak",
    sl: "Slovenian",
    sr: "Serbian",
    sv: "Swedish",
    th: "Thai",
    tr: "Turkish",
    uk: "Ukrainian",
    ur: "Urdu",
    vi: "Vietnamese",
    "zh-Hans": "Chinese (Simplified)",
    "zh-Hant": "Chinese (Traditional)",
    zh: "Chinese",
  },
  "PLATFORM": {
    win: "Windows",
    lin: "Linux",
    mac: "macOS",
    ios: "iOS",
    and: "Android",
    dvd: "DVD",
    bdp: "Blu-ray",
    ps1: "PlayStation",
    ps2: "PlayStation 2",
    ps3: "PlayStation 3",
    ps4: "PlayStation 4",
    ps5: "PlayStation 5",
    psp: "PlayStation Portable",
    psv: "PlayStation Vita",
    xb1: "Xbox One",
    xb3: "Xbox Series X/S",
    xbo: "Xbox",
    swi: "Nintendo Switch",
    wii: "Wii",
    wiu: "Wii U",
    nds: "Nintendo DS",
    n3d: "Nintendo 3DS",
    web: "Web",
  },
  "LENGTH": {
    1: "Very Short",
    2: "Short",
    3: "Medium",
    4: "Long",
    5: "Very Long",
  },
  "TAG_CATEGORY": {
    "cont": "Content",
    "ero": "Sexual Content",
    "tech": "Technical",
  }
} as const
