export const ICON = {
  "LANGUAGE": {
    ar: "icon-lang-ar",
    be: "icon-lang-be",
    bg: "icon-lang-bg",
    ca: "icon-lang-ca",
    ck: "icon-lang-ck",
    cs: "icon-lang-cs",
    da: "icon-lang-da",
    de: "icon-lang-de",
    el: "icon-lang-el",
    en: "icon-lang-en",
    eo: "icon-lang-eo",
    es: "icon-lang-es",
    eu: "icon-lang-eu",
    fa: "icon-lang-fa",
    fi: "icon-lang-fi",
    fr: "icon-lang-fr",
    ga: "icon-lang-ga",
    gd: "icon-lang-gd",
    he: "icon-lang-he",
    hi: "icon-lang-hi",
    hr: "icon-lang-hr",
    hu: "icon-lang-hu",
    id: "icon-lang-id",
    it: "icon-lang-it",
    iu: "icon-lang-iu",
    ja: "icon-lang-ja",
    kk: "icon-lang-kk",
    ko: "icon-lang-ko",
    la: "icon-lang-la",
    lt: "icon-lang-lt",
    lv: "icon-lang-lv",
    mk: "icon-lang-mk",
    ms: "icon-lang-ms",
    nl: "icon-lang-nl",
    no: "icon-lang-no",
    pl: "icon-lang-pl",
    "pt-br": "icon-lang-pt-br",
    "pt-pt": "icon-lang-pt-pt",
    pt: "icon-lang-pt-pt",
    ro: "icon-lang-ro",
    ru: "icon-lang-ru",
    sk: "icon-lang-sk",
    sl: "icon-lang-sl",
    sr: "icon-lang-sr",
    sv: "icon-lang-sv",
    ta: "icon-lang-ta",
    th: "icon-lang-th",
    tr: "icon-lang-tr",
    uk: "icon-lang-uk",
    ur: "icon-lang-ur",
    vi: "icon-lang-vi",
    "zh-Hans": "icon-lang-zh-Hans",
    "zh-Hant": "icon-lang-zh-Hant",
    zh: "icon-lang-zh",
  },
  "PLATFORM": {
    win: "icon-plat-win",
    lin: "icon-plat-lin",
    mac: "icon-plat-mac",
    ios: "icon-plat-ios",
    and: "icon-plat-and",
    dvd: "icon-plat-dvd",
    bdp: "icon-plat-bdp",
    ps1: "icon-plat-ps1",
    ps2: "icon-plat-ps2",
    ps3: "icon-plat-ps3",
    ps4: "icon-plat-ps4",
    ps5: "icon-plat-ps5",
    psp: "icon-plat-psp",
    psv: "icon-plat-psv",
    xb1: "icon-plat-xb1",
    xb3: "icon-plat-xb3",
    xbo: "icon-plat-xbo",
    swi: "icon-plat-swi",
    wii: "icon-plat-wii",
    wiu: "icon-plat-wiu",
    nds: "icon-plat-nds",
    n3d: "icon-plat-n3d",
    web: "icon-plat-web",
  },
  "RELEASE": {
    download: "icon-rel-download",
    disk: "icon-rel-disk",
    cartridge: "icon-rel-cartridge",
    v1: "icon-rel-voiced icon-rel-v1", // Not voiced
    v2: "icon-rel-voiced icon-rel-v2", // Only ero scenes voiced
    v3: "icon-rel-voiced icon-rel-v3", // Partially voiced
    v4: "icon-rel-voiced icon-rel-v4", // Fully voiced
    complete: "icon-rtcomplete",
    partial: "icon-rtpartial",
    trial: "icon-rttrial",
    notes: "icon-rel-notes",
    free: "icon-rel-free",
    nonfree: "icon-rel-nonfree",
    external: "icon-external",
  },
  "CHARACTER": {
    m: "icon-char-m",
    f: "icon-char-f",
    b: "icon-char-b",
    n: "icon-char-n",
  },
  "CHARACTER_SEX_COLOR": {
    m: "charsex-m",
    f: "charsex-f",
    b: "charsex-b",
    n: "charsex-n",
  },
} as const
